[package]
name = "hwid"
version = "0.2.0"
authors = ["S Stewart <iamtheworst@programmer.net>"]
edition = "2021"
license-file = "LICENSE"

# https://stackoverflow.com/a/51821632/364875
[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.6"

[dependencies]
thiserror = "1.0.31"
