name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        system: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.system }}
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cargo build --verbose
    - name: Test
      run: |
        cargo run --example get_hwid
