name: CI

on: [push]

jobs:
  build:
    runs-on: ["ubuntu-latest", "windows-latest", "macos-latest"]
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cargo build --verbose
    - name: Test
      run: |
        cargo run --example get_hwid
